/**
 * exportPdf.ts
 * Pure-jsPDF text renderer for EdLearn study notes.
 *
 * Uses NO html2canvas — content is read directly from the structured
 * generatedContent JSON and drawn with jsPDF's own text APIs.
 * This sidesteps the html2canvas limitation of not supporting modern CSS
 * colour functions (oklch / lab / lch / oklab) used by Tailwind v4.
 *
 * Layout per page (A4 portrait, mm units):
 *   Header  18 mm  – "EdLearn" brand + topic / day / difficulty
 *   Content        – rendered text blocks, auto page-break
 *   Footer  12 mm  – "Generated by EdLearn" + "Page N"
 *   Watermark      – "EdLearn" tiled diagonally at 4 % opacity
 */

import jsPDF from 'jspdf';

// ── A4 page geometry ────────────────────────────────────────────────────────
const PW            = 210;
const PH            = 297;
const HEADER_H      = 18;
const FOOTER_H      = 12;
const MARGIN        = 16;
const CONTENT_W     = PW - MARGIN * 2;
const CONTENT_TOP   = HEADER_H + 7;
const CONTENT_BOTTOM = PH - FOOTER_H - 5;

// ── Exported types ───────────────────────────────────────────────────────────
export interface NoteContent {
  title?: string;
  difficulty?: string;
  introduction?: string;
  outline?: string[];
  contentBlocks?: Array<{
    heading?: string;
    content?: string;
    codeExample?: string;
    language?: string;
  }>;
  summary?: string;
  sources?: Array<{ label?: string; url?: string }>;
}

export interface ExportOptions {
  /** The structured JSON returned by /api/generate */
  content: NoteContent;
  topicTitle: string;
  dayNumber: number;
  difficulty?: string;
}

// ── Internal render state (reset per export call) ────────────────────────────
class Renderer {
  pdf: jsPDF;
  y  : number;
  page: number;
  topicTitle: string;
  dayNumber : number;
  difficulty: string;

  constructor(opts: Required<ExportOptions>) {
    this.pdf        = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    this.y          = CONTENT_TOP;
    this.page       = 1;
    this.topicTitle = opts.topicTitle;
    this.dayNumber  = opts.dayNumber;
    this.difficulty = opts.difficulty;
  }

  // ── Page chrome ───────────────────────────────────────────────────────────
  private watermark() {
    this.pdf.saveGraphicsState();
    this.pdf.setGState(this.pdf.GState({ opacity: 0.04 }));
    this.pdf.setFont('helvetica', 'bold');
    this.pdf.setFontSize(56);
    this.pdf.setTextColor(79, 70, 229);
    for (let x = -PW * 0.4; x < PW * 1.5; x += 60) {
      for (let y = 0; y < PH * 1.5; y += 60) {
        this.pdf.text('EdLearn', x, y, { angle: 45 });
      }
    }
    this.pdf.restoreGraphicsState();
  }

  private header() {
    const p = this.pdf;
    p.setFillColor(15, 17, 23);
    p.rect(0, 0, PW, HEADER_H, 'F');

    p.setFillColor(99, 102, 241);
    p.rect(0, 0, 3.5, HEADER_H, 'F');

    p.setFont('helvetica', 'bold');
    p.setFontSize(14);
    p.setTextColor(255, 255, 255);
    p.text('Ed', 7, 11.5);
    p.setTextColor(99, 102, 241);
    p.text('Learn', 17.5, 11.5);

    p.setFont('helvetica', 'normal');
    p.setFontSize(7.5);
    p.setTextColor(148, 163, 184);
    p.text(`Day ${this.dayNumber}  ·  ${this.difficulty}`, PW - MARGIN, 8.5, { align: 'right' });

    p.setFont('helvetica', 'bold');
    p.setFontSize(9);
    p.setTextColor(226, 232, 240);
    const t = this.topicTitle.length > 60 ? this.topicTitle.slice(0, 57) + '…' : this.topicTitle;
    p.text(t, PW - MARGIN, 15, { align: 'right' });

    p.setDrawColor(51, 65, 85);
    p.setLineWidth(0.25);
    p.line(0, HEADER_H, PW, HEADER_H);
  }

  private footer() {
    const p = this.pdf;
    const y = PH - FOOTER_H;
    p.setFillColor(15, 17, 23);
    p.rect(0, y, PW, FOOTER_H, 'F');
    p.setDrawColor(51, 65, 85);
    p.setLineWidth(0.25);
    p.line(0, y, PW, y);

    p.setFont('helvetica', 'italic');
    p.setFontSize(7.5);
    p.setTextColor(100, 116, 139);
    p.text('Generated by EdLearn · AI-Powered Study Notes', MARGIN, y + 7.5);

    p.setFont('helvetica', 'bold');
    p.setTextColor(148, 163, 184);
    p.text(`Page ${this.page}`, PW - MARGIN, y + 7.5, { align: 'right' });
  }

  private newPage() {
    this.pdf.addPage();
    this.page++;
    this.y = CONTENT_TOP;
    this.watermark();
    this.header();
    this.footer();
  }

  private ensure(needed: number) {
    if (this.y + needed > CONTENT_BOTTOM) this.newPage();
  }

  // ── Text helpers ──────────────────────────────────────────────────────────
  divider() {
    this.y += 3;
    this.pdf.setDrawColor(210, 210, 220);
    this.pdf.setLineWidth(0.3);
    this.pdf.line(MARGIN, this.y, PW - MARGIN, this.y);
    this.y += 4;
  }

  heading(text: string, level: 1 | 2 | 3) {
    if (!text?.trim()) return;
    const cfg = {
      1: { size: 22, lh: 9.5, bold: true,  color: [10,  10,  40]  as [number,number,number], mt: 4, mb: 4 },
      2: { size: 13, lh: 6.5, bold: true,  color: [20,  20,  20]  as [number,number,number], mt: 7, mb: 3 },
      3: { size: 8.5,lh: 4.5, bold: true,  color: [79,  70,  229] as [number,number,number], mt: 5, mb: 2 },
    }[level];

    this.y += cfg.mt;
    this.ensure(cfg.lh * 2 + cfg.mb);

    this.pdf.setFontSize(cfg.size);
    this.pdf.setFont('helvetica', cfg.bold ? 'bold' : 'normal');
    this.pdf.setTextColor(...cfg.color);

    const lines = this.pdf.splitTextToSize(text, CONTENT_W);
    for (const line of lines) {
      this.ensure(cfg.lh);
      this.pdf.text(line, MARGIN, this.y);
      this.y += cfg.lh;
    }
    this.y += cfg.mb;
  }

  paragraph(text: string, indent = 0) {
    if (!text?.trim()) return;
    const LH = 5.1;
    this.pdf.setFontSize(9.5);
    this.pdf.setFont('helvetica', 'normal');
    this.pdf.setTextColor(50, 52, 65);

    const lines = this.pdf.splitTextToSize(text.trim(), CONTENT_W - indent);
    for (const line of lines) {
      this.ensure(LH);
      this.pdf.text(line, MARGIN + indent, this.y);
      this.y += LH;
    }
    this.y += 2;
  }

  bullet(num: number, text: string) {
    const LH = 5;
    this.pdf.setFontSize(9);
    this.pdf.setFont('helvetica', 'bold');
    this.pdf.setTextColor(99, 102, 241);
    this.ensure(LH + 1);
    this.pdf.text(`${num}.`, MARGIN, this.y);

    this.pdf.setFont('helvetica', 'normal');
    this.pdf.setTextColor(50, 52, 65);
    const lines = this.pdf.splitTextToSize(text, CONTENT_W - 10);
    for (let i = 0; i < lines.length; i++) {
      if (i > 0) this.ensure(LH);
      this.pdf.text(lines[i], MARGIN + 10, this.y);
      this.y += LH;
    }
    this.y += 1;
  }

  codeBlock(code: string, language: string) {
    if (!code?.trim()) return;
    const MONO_SIZE = 7.5;
    const LINE_H    = 3.8;
    const PAD       = 4;
    const LANG_H    = 7;

    this.pdf.setFontSize(MONO_SIZE);
    this.pdf.setFont('courier', 'normal');
    const lines   = this.pdf.splitTextToSize(code.trim(), CONTENT_W - PAD * 2);
    const blockH  = lines.length * LINE_H + PAD * 2 + LANG_H;

    this.ensure(blockH + 2);

    const bx = MARGIN;
    const by = this.y;
    const bw = CONTENT_W;

    // Background + border
    this.pdf.setFillColor(246, 248, 250);
    this.pdf.roundedRect(bx, by, bw, blockH, 2, 2, 'F');
    this.pdf.setDrawColor(209, 213, 219);
    this.pdf.setLineWidth(0.25);
    this.pdf.roundedRect(bx, by, bw, blockH, 2, 2, 'S');

    // Language label
    this.pdf.setFont('courier', 'bold');
    this.pdf.setFontSize(7);
    this.pdf.setTextColor(99, 102, 241);
    this.pdf.text(language || 'code', bx + PAD, by + 5);

    // Separator
    this.pdf.setDrawColor(209, 213, 219);
    this.pdf.line(bx, by + LANG_H, bx + bw, by + LANG_H);

    // Code lines
    this.pdf.setFont('courier', 'normal');
    this.pdf.setFontSize(MONO_SIZE);
    this.pdf.setTextColor(30, 30, 30);
    let cy = by + LANG_H + PAD;
    for (const line of lines) {
      this.pdf.text(line, bx + PAD, cy);
      cy += LINE_H;
    }

    this.y += blockH + 5;
  }

  // ── Render full notes ─────────────────────────────────────────────────────
  render(content: NoteContent) {
    // First page chrome
    this.watermark();
    this.header();
    this.footer();

    // Title
    this.heading(content.title || this.topicTitle, 1);

    if (content.difficulty) {
      this.pdf.setFontSize(8.5);
      this.pdf.setFont('helvetica', 'bold');
      this.pdf.setTextColor(79, 70, 229);
      this.pdf.text(content.difficulty.toUpperCase(), MARGIN, this.y);
      this.y += 6;
    }

    this.divider();

    // Introduction
    if (content.introduction) {
      this.heading('Introduction', 3);
      this.paragraph(content.introduction);
      this.y += 2;
    }

    // Outline / Core concepts
    if (content.outline?.length) {
      this.heading('Core Concepts Covered', 3);
      content.outline.forEach((item, i) => this.bullet(i + 1, item));
      this.y += 3;
    }

    // Content blocks
    if (content.contentBlocks?.length) {
      this.divider();
      for (const block of content.contentBlocks) {
        if (block.heading) this.heading(block.heading, 2);
        if (block.content) {
          block.content.split(/\n\n+/).forEach(p => this.paragraph(p.trim()));
        }
        if (block.codeExample) {
          this.codeBlock(block.codeExample, block.language || 'code');
        }
      }
    }

    // Summary
    if (content.summary) {
      this.divider();
      this.heading('Summary & Takeaways', 3);
      this.paragraph(content.summary);
    }

    // Sources
    if (content.sources?.length) {
      this.divider();
      this.heading('References & Sources', 3);
      content.sources.forEach((src, i) => {
        const line = `[${i + 1}] ${src.label || ''}${src.url ? '  ' + src.url : ''}`;
        this.paragraph(line, 4);
      });
    }
  }

  save(topicTitle: string, dayNumber: number) {
    const safe = topicTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0, 40);
    this.pdf.save(`edlearn_day${dayNumber}_${safe}.pdf`);
  }
}

// ── Public entry point ────────────────────────────────────────────────────────
export async function exportNotesPdf(opts: ExportOptions): Promise<void> {
  const r = new Renderer({
    content    : opts.content,
    topicTitle : opts.topicTitle,
    dayNumber  : opts.dayNumber,
    difficulty : opts.difficulty ?? 'Intermediate',
  });
  r.render(opts.content);
  r.save(opts.topicTitle, opts.dayNumber);
}
